### ISSUE TITLE
[bug] [0.7.0] Not redirecting after predicate returns false

### ISSUE THREAD

**Issue by andrewmclagan** [mjrussell/redux-auth-wrapper#71] opened 2016-08-12 01:42 UTC
# Issue

When my auth wrapper returns false from predicate the `redux-auth-wrapper` does not redirect to `/login` rather presents a blank page (not rendering the child routes).

I have logged the results of `predicate` to the terminal and it is returning false after my `logout` action has been executed:

Auth Wrapper:

``` javascript
export const IsSuperUser = UserAuthWrapper({
  wrapperDisplayName: 'IsSuperUser',
  authSelector: state => userSelector(state),
  predicate: user => {
    console.log('predicate', isSuperUser(user) && isLoggedIn(user)); // returns false
    return isSuperUser(user) && isLoggedIn(user);
  },
});
```

Routes:

``` javascript
const Authenticated = IsSuperUser((props) => props.children);

export default () => {

  return (
    <Route component={Authenticated}>
      <Route path="/admin" component={Root}>
        <IndexRoute component={Dashboard} />
        <Route path="/admin/jobs(/:status)" component={Jobs} />
        <Route path="/admin/job/create" component={CreateJob} />
        <Route path="/admin/job/:jobId/update" component={UpdateJob} />
        <Route path="/admin/organisations" component={Organisations} />
        <Route path="/admin/organisation/create" component={CreateOrganisation} />
        <Route path="/admin/purchase" component={Purchase} />
        <Route path="/admin/invoices" component={Invoices} />
      </Route>
    </Route>
  );
};

```
# environment

``` bash
>> node --version
v6.3.1
>> npm --version
3.10.3
```

``` json
    "redux": "^3.5.2",
    "react-router": "2.5.2",
    "react-router-redux": "^4.0.5",
    "redux-auth-wrapper": "^0.7.0",
```

**Comment by mjrussell** [comment] 2016-08-12 01:51
@andrewmclagan looking into this now, is this a regression? Did it work in 0.6?

**Comment by andrewmclagan** [comment] 2016-08-12 01:56
Ah sorry, no not a regression. This is happening also on `0.6.0` I should have been clearer.

**Comment by mjrussell** [comment] 2016-08-12 02:05
Oh thanks, where are you trying to redirect to?

The default failureRedirectPath is to `/login` and I don't see a path for that (although you might be splitting your routes into multiple files). It could be that that path doesn't exist in your app your view wont change unless react-router matches on the path.

Also if you are using the `routerMiddleware` from `react-router-redux` you can dispatch router actions instead to see if its trying to dispatch but not happening (view it with `redux-logger-middleware` or devTools)
```js
import { routerActions } from 'react-router-redux'

export const IsSuperUser = UserAuthWrapper({
  wrapperDisplayName: 'IsSuperUser',
  authSelector: state => userSelector(state),
  redirectAction: routerActions.replace,
  predicate: user => {
    console.log('predicate', isSuperUser(user) && isLoggedIn(user)); // returns false
    return isSuperUser(user) && isLoggedIn(user);
  },
});
```

**Comment by andrewmclagan** [comment] 2016-08-12 07:08
Yes, my routes are composited across different files:

Root route file:
````javascript
import React from 'react';
import { Route, IndexRedirect } from 'react-router';
import organisationRoutes from 'containers/_organisation/routes';
import adminRoutes from 'containers/_admin/routes';
import {
  App,
  NotFound,
  Login,
  PasswordRecover,
  PasswordReset,
  OrganisationSignup,
} from 'containers';

const Routes = (store) => {

  return (
    <Route path="/" component={App}>

      <IndexRedirect to="/login" />
      <Route path="/login" component={Login} />
      <Route path="/recover-password" component={PasswordRecover} />
      <Route path="/reset-password/:resetToken/:resetEmail" component={PasswordReset} />
      <Route path="/organisation-signup" component={OrganisationSignup} />

      {organisationRoutes()}

      {adminRoutes()}

      <Route path="*" component={NotFound} status={404} />

    </Route>
  );
};

Routes.displayName = 'Routes';

export default Routes;
````

and the relevant `adminRoutes()`:
````javascript
import React from 'react';
import { IndexRoute, Route } from 'react-router';
import { IsSuperUser } from 'library/auth';
import {
  Root,
  Dashboard,
  Jobs,
  CreateJob,
  UpdateJob,
  Organisations,
  CreateOrganisation,
  Purchase,
  Invoices,
} from 'containers/_admin';

const Authenticated = IsSuperUser((props) => props.children);

export default () => {

  return (
    <Route component={Authenticated}>
      <Route path="/admin" component={Root}>
        <IndexRoute component={Dashboard} />
        <Route path="/admin/jobs(/:status)" component={Jobs} />
        <Route path="/admin/job/create" component={CreateJob} />
        <Route path="/admin/job/:jobId/update" component={UpdateJob} />
        <Route path="/admin/organisations" component={Organisations} />
        <Route path="/admin/organisation/create" component={CreateOrganisation} />
        <Route path="/admin/purchase" component={Purchase} />
        <Route path="/admin/invoices" component={Invoices} />
      </Route>
    </Route>
  );
};
````

The `login` route exists although its in the roo routes file, could this be effecting it? I don't think it would?

I swapped out `'react-router-redux'` for the `redirectAction` and no route change gets dispatched. Only my `LOGOUT_REQUEST` + `LOGOUT_SUCCESS` actions that modify the auth state.  That in turn causes `predicate` to return false. Although no route transition is dispatched.

hmm....

**Comment by mjrussell** [comment] 2016-08-12 16:23
Its not a problem to split the routes, is there any chance you can create a small example for this? I don't see anything immediately wrong with your setup, but I know the predicate and redirect is working properly in the tests and in the basic example.

**Comment by andrewmclagan** [comment] 2016-08-13 02:14
Absolutely, I will create an example repo.

**Comment by andrewmclagan** [comment] 2016-08-25 04:16
still planning on doing this, just have not had time.

**Comment by mjrussell** [comment] 2016-08-25 04:57
No worries! I don't mind leaving this open.

**Comment by andrewmclagan** [comment] 2016-09-14 04:58
Okay sorry for the long delay been very busy (still have not created that repo yet...)

Although looking into the issue further it is still occurring on `0.8.0`.

It seems if `authSelector:` returns an object and `predicate:` returns false no child components are rendered and no redirect takes place.

**Comment by mjrussell** [comment] 2016-09-14 16:12
Hmm I don't believe that there is any issue with the authSelector returning and object and the predicate returning false. The examples do that exact thing for the [admin wrappers](https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/loading/app.js#L47) and the default predicate returns false for an empty object. 

It sounds like to me that your predicate is working properly and the wrapper is rendering null since it expects to be redirected immediately but something is not setup properly in your routes or with react-router/react-router-redux and that prevents the redirect from occurring. You could verify this by using the new `FailureComponent` to display an alternative component when the predicate returns false. This will cause the wrapper to not redirect but can isolate the problem to your router/redirection setup.

Something like:


```
const testFailure = () => <h1>The predicate is working properly</h1>

UserAuthWrapper({
...
FailureComponent: testFailure
...
})
```

**Comment by codereviewvideos** [comment] 2016-10-07 10:01
Hi, 

I saw the exact same issue. The problem in my case was that I had not included the `routerMiddleware` in my store.

https://github.com/reactjs/react-router-redux#what-if-i-want-to-issue-navigation-events-via-redux-actions

Adding in the middleware immediately fixed the issue. 

Hope it helps :)

Chris

**Comment by andrewmclagan** [comment] 2016-10-07 22:25
Thanks! Although we are applying our `routerMiddleware` 

````javascript
  const middlewares = [
    asyncThunkMiddleware(api),
    refreshCookieMiddleware,
    routerMiddleware(history),
  ];

  const enhancers = [
    applyMiddleware(...middlewares),
    devtools(),
  ];

  const store = _createStore(
    reducer,
    data,
    compose(...enhancers)
  );

````

Does anyone know if the order we apply middleware is important in regards ot this issue? Im now almost certain that its an issue with our store.

**Comment by pzmudzinski** [comment] 2016-10-12 18:52
Having the same issue - is it supposed to work with latest `react-router` version? I see it's using `this.context.router` instead of `this.props.router` under the hood.
This is my setup ( I am using `Immutable.js`):
```
import { isAuthenticated, isAuthenticating } from '../redux/reducers/loginStore';
export const Authenticated = UserAuthWrapper({
    authSelector: (state) => {
      const loginStore = state.get('loginStore');
      return loginStore;
    },
    authenticatingSelector: state => isAuthenticating(state),
    predicate: (state) => {
      return isAuthenticated(state) // returns false
    },
    redirectAction: (newLoc) => (dispatch) => {
      console.log('REDIRECT', newLoc, dispatch, replace); // not called
      dispatch(replace(newLoc));
    },
    FailureComponent: testFailure,
    wrapperDisplayName: 'UserIsAuthenticated'
});```

**Comment by mjrussell** [comment] 2016-10-12 19:54
@pzmudzinski what version do you mean when you say latest? It supports 2.x and probably any 3.x builds. I haven't looked at their new 4.x stuff but I don't think its been released.

It is only using context.router if you don't specify a routerAction which you are. You need to add the `routerMiddleware` from `react-router-redux` as specified [here](https://github.com/reactjs/react-router-redux#what-if-i-want-to-issue-navigation-events-via-redux-actions) if you want to use the redux actions for navigation.

**Comment by mjrussell** [comment] 2016-10-12 19:55
@andrewmclagan nothing jumps out at me as wrong with your store setup. Although I am curious how you are passing down your history to both your store and your Router. If you accidentally create it twice or don't import the same one then you can run into issues.

**Comment by andrewmclagan** [comment] 2016-10-12 22:42
We are syncing router and store history as follows, seems correct to me?

````javascript
import { Router, applyRouterMiddleware, browserHistory } from 'react-router';


const store = createStore(browserHistory, api);
const history = syncHistoryWithStore(browserHistory, store);

/**
 * Starts the app
 *
 * @author Andrew McLagan
 */
function bootstrap() {

  console.log('Booting app...');

  store.dispatch(fetchTaxonomies());

  if (window.devToolsExtension) {
    window.devToolsExtension.updateStore(store);
  }

  const component = (
    <Router history={history} render={applyRouterMiddleware(useScroll())}>
      {Routes}
    </Router>
  );

  ReactDOM.render(
    <Provider store={store} key="provider">
      {component}
    </Provider>,
    document.getElementById('app')
  );
}
````

**Comment by mjrussell** [comment] 2016-10-12 23:04
Yeah, that looks fine... I thought there might be a chance you were using createHistory or something inside both your store config and in the Router setup which would create 2 history objects and could definitely cause what you are seeing. 

But using the browserHistory singleton this way should be fine. Back to the drawing board 😄

**Comment by andrewmclagan** [comment] 2016-10-13 02:17
haha :-(

**Comment by Blackclaws** [comment] 2016-11-05 19:16
I actually have a rather similar problem. I want to Unit Test my custom declared AuthWrappers that are defined for my project. If I try to do that by wrapping the components like:

      <Provider store={store}>
        <div>
        {userIsAuthenticated(testComponent)}
        </div>
      </Provider>

Without using a Router. I don't get anything rendered. Not even the auth selector is called for some reason.

**Comment by mjrussell** [comment] 2016-11-05 19:17
@Blackclaws that is a pretty different use case, can you open another issue for this question?

**Comment by andrewmclagan** [comment] 2016-11-06 04:16
@mjrussell an update: We have some space in the next couple of weeks, I'm going to get one of our devs to spend some time and solve this issue once and for all! Will report our findings back here. At present we are still simply doing a `window.reload()` workaround.

**Comment by mjrussell** [comment] 2016-11-06 05:18
@andrewmclagan sounds good, if at some point you or one or you devs wants to do a screen sharing/debugging session Im happy to do that as well

**Comment by DontRelaX** [comment] 2016-12-03 20:02
@andrewmclagan faced something similar, seems that `predicate` function runs twice before redirection:
1. with old props
2. with new props

if both executions return same value there no redirection performed. In code:
```
  var isAuthorized = function isAuthorized(authData) {
    return predicate(authData);
  };
...
      {
        key: 'componentWillReceiveProps',
        value: function componentWillReceiveProps(nextProps) {
          var willBeAuthorized = isAuthorized(nextProps.authData);
          var willbeAuthenticating = nextProps.isAuthenticating;
          var wasAuthorized = isAuthorized(this.props.authData);
          var wasAuthenticating = this.props.isAuthenticating;

          // Don't bother to redirect if:
          // 1. currently authenticating or FailureComponent is set
          if (willbeAuthenticating || !shouldRedirect) return;

          // Redirect if:
          if ( // 1. Was authorized, but no longer
          wasAuthorized && !willBeAuthorized ||
          // 2. Was not authorized and authenticating
          wasAuthenticating && !willBeAuthorized) {
            createRedirect(nextProps.location, this.getRedirectFunc(nextProps), nextProps.failureRedirectPath);
          }
        }
      }
```
I didn't dig deep into the code so perhaps I missed something or this is not your case, just a guess.

**Comment by mjrussell** [comment] 2016-12-04 05:22
@DontRelaX yeah that is the basis of how redux-auth-wrapper works. Perform redirection in the case that the `predicate` applied to the result of `authSelector` returns false. Predicate should be  a pure function (no side effects) and return a boolean

**Comment by pietbrauer** [comment] 2016-12-05 12:57
@andrewmclagan Can you share your `window.reload()` workaround?

**Comment by andrewmclagan** [comment] 2016-12-08 16:06
````javascript
  predicate: user => {
    if (! isLoggedIn(user)) {
      window.location.reload();
    }
    return !!isLoggedIn(user);
  },
````

**Comment by mjrussell** [comment] 2016-12-08 19:47
@andrewmclagan Im going to close this issue.

Typically when people "think" they have this problem it is actually a misconfiguration of the hookup of the router to the store. I'd still be happy to work with one of your devs to figure out what is going on in your setup but I dont believe it is an issue with this library

**Closed by mjrussell** 2016-12-08 19:47 UTC

**Comment by shenders13** [comment] 2017-04-19 05:58
@andrewmclagan, my predicate function looks for a cookie too.

`const predicateHandler = () => {
  if (!Helpers.doesValidTokenExist()) {
    return false;
  }
  return true;
}`

It is only failing when I explicitly delete my cookies whilst the app is open and then try and navigate around. A white screen appears.

How did you resolve this issue?

Thanks in advance!

**Comment by andrewmclagan** [comment] 2017-04-19 15:00
I moved to localStorage...
