### ISSUE TITLE
Example for LoadingComponent

### ISSUE THREAD

**Issue by hassankhan** [mjrussell/redux-auth-wrapper#73] opened 2016-08-17 01:12 UTC
I can't seem to get it to work, are there any examples anywhere?

**Comment by mjrussell** [comment] 2016-08-17 06:37
There isn't a great example and I was playing with this last night and found a few confusing pieces. Sorry for not having better docs on this part...I'll push an updated example tomorrow. Just need to clean up a few things.

**Comment by hassankhan** [comment] 2016-08-17 13:33
No worries, I thought I was doing something silly, good to know its not just me :)

**Comment by mjrussell** [comment] 2016-08-19 08:45
I just pushed a loading example to master in 8d49052.  Let me know if that clears things up for you or if you have other questions about using LoadingComponent.

**Comment by mjrussell** [comment] 2016-08-25 15:27
@hassankhan did you have a chance to look at the example? Wondering if I can close this now

**Comment by mcrawshaw** [comment] 2016-08-27 01:04
This worked as designed for me.

**Comment by mcrawshaw** [comment] 2016-08-27 02:26
Actually, let me correct that.  It works as designed, but I think I may have a have a different problem.

I wish to display a loading widget from my server-side rendered markup while my client-side code is booting up.  I have tried using the LoadingComponent and the FailureComponent for this task.  However when specified they disable the redirect which isn't great when my client-side code is booted.

I reference the current code for selecting the component to display:
```javascript
if (isAuthorized(authData)) {
   return <DecoratedComponent authData={authData} {...otherProps} />
} else if(isAuthenticating) {
   return <LoadingComponent authData={authData} {...otherProps} />
} else {
   return FailureComponent ? <FailureComponent authData={authData} {...otherProps} /> : null
}
```

I think I require the ability to specify an "EmptyComponent" prop.

It works with this change to the code:
```javascript
if (isAuthorized(authData)) {
   return <DecoratedComponent authData={authData} {...otherProps} />
} else if(isAuthenticating) {
   return <LoadingComponent authData={authData} {...otherProps} />
} else if (FailureComponent) {
   return <FailureComponent authData={authData} {...otherProps} />
else {
   return EmptyComponent ? <EmptyComponent /> : null
}
```

@mjrussell What do you think?  Happy to submit a pull request...

**Comment by hassankhan** [comment] 2016-08-28 17:37
Sorry @mjrussell I'm on holiday at the moment, never did get the chance to have a look before I left. I'll be back a week from now, will try and report back then 😄

**Comment by mjrussell** [comment] 2016-08-29 03:41
@hassankhan no problem!

@mcrawshaw Im not sure I understand the need for the EmptyComponent. From what you described I think the LoadingComponent should be suitable, you just need your authenticatingSelector to check for a flag both for if the user is authenticating and if your client code is fully booted up.

The LoadingComponent does not disable the redirect ability, only the FailureComponent affects wether the redirect is enabled or not.

**Comment by mjrussell** [comment] 2016-09-21 06:18
I'm going to close this issue since I believe the new example explains it well and I haven't heard otherwise

**Closed by mjrussell** 2016-09-21 06:18 UTC
Labels: examples
